name: pytorch_dl

channels:
  - pytorch
  - conda-forge
  - pyg

dependencies:
  - python=3.8
  - pip
  - cudatoolkit
  - pytorch=1.8.1
  - torchvision=0.9.1
  - pytorch-scatter
  - pip:
      - -r requirements.txt
