model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val/Accuracy" # name of the logged metric which determines when model is improving
  save_top_k: 1 # save k best models (determined by above metric)
  save_last: True # additionaly always save model from last epoch
  mode: "max" # can be "max" or "min"
  verbose: False
  dirpath: "checkpoints/"
  auto_insert_metric_name: False
  filename: "epoch{epoch:02d}-val_acc{val/Accuracy:.2f}"
