_target_: src.datamodules.dadatamodule.DADataModule

src: gta5
tgt: cityscapes
data_dir: ${data_dir}
num_classes: 19
ignore_index: 250

augmentations:
  rsize: 2200
  rcrop: [896, 512]
  brightness: 0.5
  contrast: 0.5
  saturation: 0.5
  hflip: 0.5

batch_size: 64
effective_batch_size: null
num_workers: 0
pin_memory: False
