_target_: src.datamodules.dali_datamodule.IMAGENET_DALI_DataModule

# Dataset

num_classes: 1000
data_dir: ${data_dir} # data_dir is specified in config.yaml

# Dataloader

batch_size: 64
effective_batch_size: null
num_workers: 0
pin_memory: False
dali_cpu: False
