_target_: src.datamodules.pytorch_datamodule.IMAGENETDataModule

# Dataset

num_classes: 1000
data_dir: ${data_dir} # data_dir is specified in config.yaml
randaug_m: 0

# Dataloader

batch_size: 64
effective_batch_size: null
num_workers: 0
pin_memory: False
