_target_: src.datamodules.pytorch_datamodule.IMAGENETDataModule

# Dataset

num_classes: 1000
data_dir: ${data_dir} # data_dir is specified in config.yaml

# Dataloader

batch_size: 64
effective_batch_size: ${batch_size}
num_workers: 0
pin_memory: False
