_target_: src.datamodules.datamodule_cls.MNISTDataModule

# Dataset

num_classes: 10
data_dir: ${data_dir} # data_dir is specified in config.yaml
train_val_test_split: [55_000, 5_000, 10_000]

# Dataloader

batch_size: 64
effective_batch_size: null
num_workers: 0
pin_memory: False
