#!/bin/sh

#PBS -l select=1:ncpus=20:ngpus=4
#PBS -l walltime=23:59:59
#PBS -q dgx
#PBS -P 11002070
#PBS -N default
#PBS -j oe
#PBS -m abe
#PBS -M zhengzangw@gmail.com

export WORK_DIR=/home/project/11002070/zangwei/pytorch-classification
export PYTHON=/home/users/nus/e0575577/anaconda3/envs/pycls/bin/python

nscc-docker run nscc/local/pytorch:latest <<EOF
cd $WORK_DIR
$PYTHON run.py experiment=imagenet_mixerb_4k
EOF

# interactive
# ---
# qsub -I -q dgx-dev -l walltime=00:20:00 -P 11002070
